# Generated by Django 6.0.1 on 2026-02-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_candidateprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='experience_range',
            field=models.CharField(blank=True, choices=[('lt1', '< 1 year'), ('1_2', '1–2 years'), ('2_3', '2–3 years'), ('3_5', '3–5 years'), ('5_8', '5–8 years'), ('8plus', '8+ years')], default='', max_length=20),
        ),
    ]
