# Generated by Django 6.0.1 on 2026-02-04 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='applications',
                to='jobs.candidateprofile',
            ),
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
    ]
